<?php

function custom_module_form_alter(&$form, &$form_state, $form_id) {
    if ($form_id == 'node_type_form') {
        $form['display']['node_submitted']['#default_value'] = 0;
    }

    if ($form_id == 'article_node_form') {
      $form['comment_settings']['#access'] = 0;
      $form['revision_information']['#access'] = 0;
      $form['author']['#access'] = 0;
      $form['options']['#access'] = 0;
    }
}
