<?php

function special_links_follow_networks_alter(&$networks, $uid = 0) {
    $networks[$uid]['imdb'] = array(
      'title' => t('IMDB'),
      'domain' => 'imdb.com',
    );

    $networks[$uid]['drupal'] = array(
      'title' => t('Drupal.org'),
      'domain' => 'drupal.org',
    );

    $networks[$uid]['github'] = array(
      'title' => t('the Gits'),
      'domain' => 'github.com'
    );

    // print '<pre>';
    // print_r($networks);
    // print '</pre>';
}
